### ISSUE TITLE
android-simg rootfs format

### ISSUE THREAD

**Issue by FlorentRevest** [AsteroidOS/meta-asteroid#16]
Currently, images generated by the asteroid build system only take a minimal amount of space and don't fill the entire userdata partition.
This has caused several kinds of problems (like a partition getting filled quickly and preventing the system from working correctly) and generating a larger rootfs partitions should provide a better experience.
However, having large partitions may fill the release.asteroidos.org server and cause long download times. It turns out that fastboot support an "simg" file format which addresses precisely this problem. Defining a new sparse partition bbclass for OE using a tool like img2simg would be super useful.

**Comment by beschulz** [comment]
would it be an option to use img2simg to convert the images into sparse images?
I used

resize2fs 2800M asteroid-image-dory.ext4
img2sim asteroid-image-dory.ext4 asteroid-image-dory.ext4.sparse
fastboot format:ext4 userdata
fastboot flash userdata asteroid-image-dory.ext4.sparse

it appears to be working fine and the sparse image is only 357M

**Comment by FlorentRevest** [comment]
@beschulz For a detailed description of why we don't distribute simgs, I'd point you to that comment: https://github.com/AsteroidOS/asteroid/issues/31#issuecomment-348731212
Essentially, we can't get the "temporary installation" to work with simgs and I think this is very appreciated by testers who don't want to remove WearOS.
Also, we don't have data on maximum size of userdata partitions on each supported watch.

**Comment by comradekingu** [comment]
Isn't this something http://atterer.org/jigdo/ solves?

**Comment by FlorentRevest** [comment]
@comradekingu  Mhh, I don't think asking our users to download a downloader is really appropriate. I'd rather ask them to install img2simg and resize2fs.
What I think could be a good solution would be to actually resize the rootfs to fill the userdata partition from the initrd on the first boot of a real installation. This way, we don't have to redistribute both a simg and an img, we have a flexible solution that doesn't require to know the partition size of each device at compile time and we don't have to use tools such as resize2fs or img2simg.
