### ISSUE TITLE
The repacked system.img of samsung can not flash by odin

### ISSUE THREAD

**Issue by lzhh52** [AsteroidOS/meta-asteroid#22]
eg：
simg2img ./system.img.ext4 ./system.img
img2simg ./system.img ./system.img.ext4

After rename system.img.tar to system.img, package it into tar file, which cannot be brushed in with 
I want to ask, how should I do?

**Comment by FlorentRevest** [comment]
What watch are you trying to use?
Why would you want to use Odin?
Are you trying to use AsteroidOS?
"cannot be brushed in" ? I don't understand your sentence.
"How should I do"? What do you even want to do? It doesn't make any sense.
From a quick look, you seem to have reverted your img and simg parameters

**Comment by jrtberlin** [comment]
We don't support a single watch from Samsung. The question/issue is not very specific and seems totally unrelated to this project. @FlorentRevest We should close this one.
