### ISSUE TITLE
Update obsolete git.merproject.org repo to github.com/sailfishos

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/meta-asteroid#66]
Pulling from `https://git.merproject.org/` does not appear to work because that server does not appear to support tls negotiation.  For that reason, these should be changed to point to the newer `https://github.com/sailfishos` versions.

**Comment by beroset** [comment]
Just awaiting one upstream commit:  https://github.com/meta-qt5/meta-qt5/pull/432

**Comment by FlorentRevest** [comment]
I see that meta-qt5/meta-qt5#432 got merged, I'll close this issue. Feel free to re-open if it's missing something :)

**Comment by MagneFire** [comment]
Even though the PR was merged, it wasn't merged into the `honister` branch.
I've adjusted the `prepare-build.sh` script to use the `master` branch but at a fixed commit: https://github.com/AsteroidOS/asteroid/commit/bd194d1bd430a60b23c031385d28ac5b4d837f60.
